### PR TITLE
Fix pdf generation on windows (#119)

### LINKED ISSUE #119: PDF format cannot be generated on windows platform
When trying to generate the pdf format from a windows machine, asciidoctor fails with the following.
```
org.jruby.exceptions.RaiseException: (SystemCallError) Unknown error (SystemCallError) 123 - FindFirstFile
```

This behavior can be reproduced by running the existing tests on a windows host.

Here are the details of the machine I reproduced it on.
```
C:\>mvn --version
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T20:41:47+02:00)
Maven home: C:\ProgramData\chocolatey\lib\maven\apache-maven-3.6.0\bin\..
Java version: 1.8.0_201, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_201\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

[Here is the related maven output](https://github.com/rmpestano/cukedoctor/files/2847862/mvn.log)

**Note:** There were some minor fixes required in the converter tests to reach the plugin module,
there are non portable line endings and path separators expected in the converter tests.

### PR DESCRIPTION
**Pull request by thomas-breining**
PDF generation fails when executed on windows due to the following error
encountered by `asciidoctor`.
```
org.jruby.exceptions.RaiseException: (SystemCallError) Unknown error (SystemCallError) 123 - FindFirstFile
```

This is most likely a bug originating from either `asciidoctor`, `jruby`
or the combination of both.

Additionally, tests of `cukedoctor-converter` and `cucumber-spi-example`
modules have occurrences of unexpected line endings or paths separators when
executed on windows.

Closes #119

### CODE REVIEW

**Comment by thomas-breining** [comment]
Hi,

I've tried to fix the issue #119 I opened.

Since I was using maven 3.6.0 I had to upgrade maven plugins to build the project successfully.

I've kept the *upgrade* to maven 3.6.0 in a separate commit in case you preferred not to merge it.

I'm also not sure what your contribution policy is so I hope I haven't done anything forbidden.

In any case don't hesitate to let me know what you think.

**Comment by rmpestano** [comment]
Thank you very much Thomas! I'll make some tests It the plugin version upgrade doesn't affect anything (mainly the Jenkins plugin) and then will Merge ASAP.

**Comment by rmpestano** [comment]
Hi again @thomas-breining, unfortunately I was not able to make the [jenkins plugin](https://github.com/jenkinsci/cucumber-living-documentation-plugin) working with your proposed changes. I think it is related with the AsciidoctorJ upgrade and jruby-complete.

Following is what I've experienced:

* [Cukdoctor extensions](https://github.com/rmpestano/cukedoctor/tree/master/cukedoctor-extension) are not registered so in the generated documentation there is not search field, minimizable, e.g see 
`minmax::` on the generated html:

screenshot from 2019-02-10 14-11-18

* PDF generation is not working, I get the following error:

```
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/psych.rb:6: warning: already initialized constant UTF16BE
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55:in `require':
It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
org.jruby.exceptions.RaiseException: (LoadError) load error: psych -- java.lang.NoClassDefFoundError: Could not initialize class org.jruby.ext.psych.PsychEmitter
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:955)
	at uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.lib.ruby.stdlib.rubygems.core_ext.kernel_require.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55)
	at RUBY.<main>(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/yaml.rb:6)
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:955)
	at uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.lib.ruby.stdlib.rubygems.core_ext.kernel_require.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55)
	at RUBY.<main>(uri:classloader:/gems/prawn-icon-1.3.0/lib/prawn/icon/font_data.rb:1)
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:955)
	at uri_3a_classloader_3a_.jruby.kernel.kernel.require_relative(uri:classloader:/jruby/kernel/kernel.rb:13)
	at RUBY.<main>(uri:classloader:/gems/prawn-icon-1.3.0/lib/prawn/icon/font_data.rb:9)
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:955)
	at uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.lib.ruby.stdlib.rubygems.core_ext.kernel_require.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55)
	at RUBY.<main>(uri:classloader:/gems/prawn-icon-1.3.0/lib/prawn/icon.rb:1)
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:955)
	at uri_3a_classloader_3a_.jruby.kernel.kernel.require_relative(uri:classloader:/jru
```

I also tried to update [jruby-complete](https://github.com/jenkinsci/cucumber-living-documentation-plugin/blob/286f97a4ccc0d580690394633de4f98c99c43c2a/pom.xml#L85-L88) to `9.2.5.0` and [jnr-constants](https://github.com/jenkinsci/cucumber-living-documentation-plugin/blob/286f97a4ccc0d580690394633de4f98c99c43c2a/pom.xml#L54-L58) to `0.9.12` but then neither html is generated and following error is raised:

```
fev 10, 2019 2:27:10 PM org.asciidoctor.internal.JRubyAsciidoctor convertFile
SEVERE: (EINVAL) Invalid argument - /home/rmpestano/.jenkins/jobs/test/builds/8/cucumber-living-documentation/documentation.adoc
org.asciidoctor.internal.AsciidoctorCoreException: org.jruby.exceptions.SystemCallError: (EINVAL) Invalid argument - /home/rmpestano/.jenkins/jobs/test/builds/8/cucumber-living-documentation/documentation.adoc
	at org.asciidoctor.internal.JRubyAsciidoctor.convertFile(JRubyAsciidoctor.java:498)
	at org.asciidoctor.internal.JRubyAsciidoctor.convertFile(JRubyAsciidoctor.java:469)
	at com.github.cukedoctor.jenkins.CukedoctorPublisher.generateDocumentation(CukedoctorPublisher.java:312)
	at com.github.cukedoctor.jenkins.CukedoctorPublisher$2.run(CukedoctorPublisher.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.jruby.exceptions.SystemCallError: (EINVAL) Invalid argument - /home/rmpestano/.jenkins/jobs/test/builds/8/cucumber-living-documentation/documentation.adoc
	at org.jruby.RubyIO.sysopen(org/jruby/RubyIO.java:1230)
	at org.jruby.RubyFile.initialize(org/jruby/RubyFile.java:361)
	at org.jruby.RubyIO.open(org/jruby/RubyIO.java:1152)
	at RUBY.convert_file(uri:classloader:/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1595)
fev 10, 2019 2:27:10 PM hudson.init.impl.InstallUncaughtExceptionHandler$DefaultUncaughtExceptionHandler uncaughtException
SEVERE: A thread (pool-15-thread-1/91) died unexpectedly due to an uncaught exception, this may leave your Jenkins in a bad way and is usually indicative of a bug in the code.
java.lang.RuntimeException: Unexpected error on documentation generation, message org.jruby.exceptions.SystemCallError: (EINVAL) Invalid argument - /home/rmpestano/.jenkins/jobs/test/builds/8/cucumber-living-documentation/documentation.adoc, cause org.jruby.exceptions.SystemCallError: (EINVAL) Invalid argument - /home/rmpestano/.jenkins/jobs/test/builds/8/cucumber-living-documentation/documentation.adoc
	at com.github.cukedoctor.jenkins.CukedoctorPublisher$2.run(CukedoctorPublisher.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

I am running on top of Jenkins ver. 2.150.2.

**Comment by thomas-breining** [comment]
Hi, thanks for the quick feedback.

I had already seen the missing for psych error when I was trying to make the pdf generation work simply by overwriting plugin dependencies from another project.

I'm now wondering if I could make these changes work only because I had the ruby-native psych library installed on my machine.

I'll look into this and the jenkins plugin further to try and fix it.
I'll get back to you as soon as I know more.

**Comment by rmpestano** [comment]
Great, if you need any help on testing the jenkins plugin then just let me know. I can also test it directly from the plugin by using the command `mvn hpi:run`, it will start a jenkins on port 8080 with the plugin installed.

**Comment by thomas-breining** [comment]
A quick update ; I've come to the conclusion that the extension not being registered is probably caused by a known issue with asciidoctorj 1.6.x (https://github.com/asciidoctor/asciidoctorj/issues/764).

I have had some success making things work by reverting to `asciidoctorj-1.6.0-alpha.17` and making the dependencies converge between cukedoctor modules, the jenkins plugin and asciidoctor.

I'm completely there yet but I'll keep you posted.

**Comment by rmpestano** [comment]
Hi @thomas-breining,

great news! thank you very much for diving into this.

Looks like AsciidoctorJ 1.6.2 may be released this week with the fix for the extensions.

**Comment by thomas-breining** [comment]
I think I've managed it now.

Here are the docs generated from Jenkins ver. 2.73.3 (`mvn hpi:run`) by building the cukedoctor project.
[documentation.pdf](https://github.com/rmpestano/cukedoctor/files/2862076/documentation.pdf)
[documentation.adoc.txt](https://github.com/rmpestano/cukedoctor/files/2862088/documentation.adoc.txt)
[documentation.html.txt](https://github.com/rmpestano/cukedoctor/files/2862089/documentation.html.txt)

The dynamic HTML theme selection from jenkins seems broken though, when I select any other theme I get the following exception.
```
java.nio.file.NoSuchFileException: themes\colony.css
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.Files.readAllBytes(Files.java:3152)
	at com.github.cukedoctor.jenkins.DocsRenderer.doIndex(DocsRenderer.java:43)
...
```
It works if I browse the file directly. I'm not sure if I broke it from jenkins or if it was a pre-existing issue.

Making this work required to [tweak the cucumber-living-documentation-plugin dependencies](https://github.com/thomas-breining/cucumber-living-documentation-plugin/commit/19411e977776695c5c786d5ed81be5198bca05a1) a little.

In the end, the PDF generation issue only required to upgrade jruby version on paper.
That was not sufficient in practice because of the way the dependencies were declared ; asciidoctor pulled its own version because the wrong artifact was excluded and the jenkins plugin also had its own version declared.

I thought it could be nice to try and cleanup the dependency tree and enforce its convergence to try and avoid these issues as much as possible in the future. I started to do it but it proved a bit tricky, especially in the maven plugin, so I let it lie for now. Let me know what you think about it, I might be able to help a little if you want to pursue that.

I'll try the next asciidoctorj release to check if the extension lookup mechanism has been fixed.

**Comment by rmpestano** [comment]
This is awesome, if I find some test I'll try to build AsciidoctorJ locally to make sure next version will fix the extension loading issue.

Again, thank you very much for your contributions so far!

**Comment by rmpestano** [comment]
> The dynamic HTML theme selection from jenkins seems broken though, when I select any other theme I get the following exception.

This is related with the extension loading issue, themes are copied to jenkins job workspace on the themeExtension, [see here](https://github.com/rmpestano/cukedoctor/blob/0e86dedbd8498ad551ce314a219e78cbabb7ff7d/cukedoctor-extension/src/main/java/com/github/cukedoctor/extension/CukedoctorThemeExtension.java#L32-L40).

**Comment by rmpestano** [comment]
I have tested the jenkins plugin on [your fork](https://github.com/thomas-breining/cucumber-living-documentation-plugin) with [AsciidoctorJ 1.6.2](https://github.com/asciidoctor/asciidoctorj/releases/tag/v1.6.2) but got the following error:

```
SEVERE: (EINVAL) Invalid argument - /home/PROCERGS.REDERS/rafael-pestano/projetos/cucumber-living-documentation-plugin-update/work/jobs/test/builds/3/cucumber-living-documentation/documentation.adoc
org.asciidoctor.internal.AsciidoctorCoreException: org.jruby.exceptions.SystemCallError: (EINVAL) Invalid argument - /home/PROCERGS.REDERS/rafael-pestano/projetos/cucumber-living-documentation-plugin-update/work/jobs/test/builds/3/cucumber-living-documentation/documentation.adoc
	at org.asciidoctor.internal.JRubyAsciidoctor.convertFile(JRubyAsciidoctor.java:498)
	at org.asciidoctor.internal.JRubyAsciidoctor.convertFile(JRubyAsciidoctor.java:469)
	at com.github.cukedoctor.jenkins.CukedoctorPublisher.generateDocumentation(CukedoctorPublisher.java:311)
	at com.github.cukedoctor.jenkins.CukedoctorPublisher$2.run(CukedoctorPublisher.java:287)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.jruby.exceptions.SystemCallError: (EINVAL) Invalid argument - /home/PROCERGS.REDERS/rafael-pestano/projetos/cucumber-living-documentation-plugin-update/work/jobs/test/builds/3/cucumber-living-documentation/documentation.adoc
	at org.jruby.RubyIO.sysopen(org/jruby/RubyIO.java:1233)
	at org.jruby.RubyFile.initialize(org/jruby/RubyFile.java:361)
	at org.jruby.RubyIO.open(org/jruby/RubyIO.java:1155)
	at RUBY.convert_file(uri:classloader:/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1595)
```
I updated jruby-complete to `9.2.6.0` as AsciidocotrJ release notes suggests so maybe thats the cause.

**Comment by thomas-breining** [comment]
I'm glad I can be of some help, thanks to you for maintaining these great plugins.
I couldn't find many solutions to generate PDF cucumber reports and yours renders the best looking docs imho.

I've taken another look at the theme selection and found that it was another windows paths thing.
I could fix it [in my fork](https://github.com/thomas-breining/cucumber-living-documentation-plugin/commit/edeeb03096a7669f4c1f123e3e6c4a429b7d0530).

I will try to make asciidoctorj 1.6.2 work on my side as well, see if I run into that same issue you did.

**Comment by thomas-breining** [comment]
I could reproduce the `EINVAL` issue on linux but not on windows.

This seems to occur with jruby version `9.2.x.x` regardless of the the asciidoctorj version (`>= 1.6.0-alpha.6`).

I'll have to take more time to pinpoint exactly the last version of jruby that doesn't show the issue and see if PDF generation works on windows with it.

Also, I've found the same issue reported in the asciidoctorj project https://github.com/asciidoctor/asciidoctorj/issues/471.

**Comment by rmpestano** [comment]
See comments on #119.

**Pull request closed without merging**
