### PR TITLE
cucumber-jvm 5.x compatibility: feature ordering via tags and DocString enrichment via tags or content type

### PR DESCRIPTION
**Pull request by andrewesweet**
As discussed in issue #117, feature and step comments are not supported in the out-of-the-box JSON output in cucumber-jvm 2.x and later.

This PR adds an alternative mechanism to order features (#40) by means of a feature tag e.g. "@order-42". Support for order comments is maintained.

In this implementation, the order tag itself turns up in the generated documentation as a tag for all scenarios within that feature (example below). Arguably we may want to remove these cukedoctor-specific tags from the generated docs.

`==== Scenario: Scenario feature 2
[small]#tags: @order-1#`

### CODE REVIEW

**Comment by rmpestano** [comment]
Oww very nice! 

Can we skip the order tags in generated docs? I think we should not have cukedoctor related things in generated documentation, WDYT?

Thank you!

**Comment by rmpestano** [comment]
Also, I almost forgot, there is another alternative to add comments to cucumber json report via a formate, [see here](https://github.com/rmpestano/cukedoctor/issues/132#issuecomment-610826501).

I didn't test the approach but if it works then we can use Cukedoctor with comments instead of creating custom tags.

**Comment by andrewesweet** [comment]
> Oww very nice!
> 
> Can we skip the order tags in generated docs? I think we should not have cukedoctor related things in generated documentation, WDYT?
> 
> Thank you!

Since writing that note about the tags remaining, it has annoyed me enough that I'm already hacking away at it. It adds a bit more complexity to the change as we now need to distinguish between a feature having tags and having _renderable_ tags.



> Also, I almost forgot, there is another alternative to add comments to cucumber json report via a formate, [see here](https://github.com/rmpestano/cukedoctor/issues/132#issuecomment-610826501).
> 
> I didn't test the approach but if it works then we can use Cukedoctor with comments instead of creating custom tags.

I tried that approach, but it did not work for feature comments, only step comments. Maybe that approach could be extended to work for feature comments, but in my cursory examination I couldn't spot how to do it. I was also motivated by https://github.com/cucumber/cucumber-jvm/issues/1329#issuecomment-388626019, which states that in general you cannot reliably list comments to Gherkin AST nodes, so we'd have no guarantee of compatibility. That being said, some of the commentary on the Gherkin 8 support project (https://github.com/orgs/cucumber/projects/6 and in particular https://github.com/cucumber/cucumber/issues/764#issue-508466385) suggests that they want to make this possible in future, although we'd like end up writing our own formatter (or future equivalent thereof) that would have to ship with cukedoctor.

**Comment by rmpestano** [comment]
Got it, let's keep the custom tags then.

For a new release I think we'll also need the `@Asciidoc` tag to enable Asciidoc in docstrings, can you work on that as well? take your time, no rush.

**Comment by andrewesweet** [comment]
I've pushed a second commit to remove '@order-' tags from the rendered document, including the case where such a tag is the only tag.

As part of this, I've found a bug caused by a change in behaviour under cucumber-jvm - feature tags are automatically cascaded to scenarios in the json, but we render tags for a scenario by iterating through feature tags then scenario tags, hence we get a doubling up in the final output. I'll raise a separate issue for that. The fix should be easy enough.



> Got it, let's keep the custom tags then.
> 
> For a new release I think we'll also need the `@Asciidoc` tag to enable Asciidoc in docstrings, can you work on that as well? take your time, no rush.

I intend to, but I'm not sure over what time period I'll be able to do it. Therefore, I'd prefer to do a PR per feature/fix, rather than one big "2.x support" PR, if that's agreeable for you?

**Comment by andrewesweet** [comment]
I've spotted a way to make this change simpler - I'll push another commit later today, I hope

**Comment by rmpestano** [comment]
> I'd prefer to do a PR per feature/fix

Sure, that's the Idea! Thank you very much for your contribution so far!

**Comment by andrewesweet** [comment]
Pushed. By fixing #134 the implementation has become much more succinct. Ready for merge, subject to your review.

**Comment by andrewesweet** [comment]
After saying I did not want one PR to rule them all, that's what I've generated. This PR now:

1. Allows feature ordering via feature tags
2. Enrichment of DocStrings via a custom content-type (as suggested by @msche in #132) or via a feature or scenario tag (as suggested by @rmpestano in #117).
3. Test assertion fixes to allow the full test suite to be executed under Windows (mostly about formatting line endings and one instance of formatting paths).

Given (3), I'd appreciate someone running the test suite under *nix and confirm it is still passing successfully.

**Comment by rmpestano** [comment]
> Given (3), I'd appreciate someone running the test suite under *nix and confirm it is still passing successfully.

It passes on MacOS here, the travis build runs on top of ubuntu so I think if travici passes then we are ok.

> (2) required a breaking change to the spi.StepsRenderer interface...

Don't worry about that, we are going to release Cukedoctor 2.x to support cucumber 2.x onwards so users will expect breaking changes.

As we are introducing the tags, can't we have `@cukedoctor` instead of `@cukedoctor-discrete`? I'm also inclined to use @Asciidoc if possible. WDYT? 

Also, thank you again for your awesome contribution!

**Comment by andrewesweet** [comment]
> As we are introducing the tags, can't we have `@cukedoctor` instead of `@cukedoctor-discrete`? I'm also inclined to use `@asciidoc` if possible. WDYT?

I'm happy to change this. Whilst `cukedoctor-discrete` is a bit verbose, it gives consistency with the step comment approach `#cukedoctor-discrete` comments. I'll update to `@asciidoc` for tags and content type too.

**Comment by rmpestano** [comment]
I'll make a couple of tests during this week (jenkins plugin) and then release 2.0 on next weekend, ok?

Thank you!

**Pull request merged**
